//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGuiX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double WindowPosLeft {
            get {
                return ((double)(this["WindowPosLeft"]));
            }
            set {
                this["WindowPosLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double WindowPosTop {
            get {
                return ((double)(this["WindowPosTop"]));
            }
            set {
                this["WindowPosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(null)]
        public string HistoryLog {
            get {
                return ((string)(this["HistoryLog"]));
            }
            set {
                this["HistoryLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RamtestCpuCacheMode {
            get {
                return ((int)(this["RamtestCpuCacheMode"]));
            }
            set {
                this["RamtestCpuCacheMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RamtestRngMode {
            get {
                return ((int)(this["RamtestRngMode"]));
            }
            set {
                this["RamtestRngMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RamtestStopOnError {
            get {
                return ((bool)(this["RamtestStopOnError"]));
            }
            set {
                this["RamtestStopOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RamtestStopOnTaskScope {
            get {
                return ((bool)(this["RamtestStopOnTaskScope"]));
            }
            set {
                this["RamtestStopOnTaskScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RamtestSizeIsAuto {
            get {
                return ((bool)(this["RamtestSizeIsAuto"]));
            }
            set {
                this["RamtestSizeIsAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint? RamtestMegabytes {
            get {
                return ((uint?)(this["RamtestMegabytes"]));
            }
            set {
                this["RamtestMegabytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public uint? RamtestSizePercent {
            get {
                return ((uint?)(this["RamtestSizePercent"]));
            }
            set {
                this["RamtestSizePercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public uint? RamtestTaskScope {
            get {
                return ((uint?)(this["RamtestTaskScope"]));
            }
            set {
                this["RamtestTaskScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public uint? RamtestThreads {
            get {
                return ((uint?)(this["RamtestThreads"]));
            }
            set {
                this["RamtestThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RamtestBeepOnError {
            get {
                return ((bool)(this["RamtestBeepOnError"]));
            }
            set {
                this["RamtestBeepOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint? RamtestErrorLimit {
            get {
                return ((uint?)(this["RamtestErrorLimit"]));
            }
            set {
                this["RamtestErrorLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RamtestStressFpu {
            get {
                return ((bool)(this["RamtestStressFpu"]));
            }
            set {
                this["RamtestStressFpu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public uint? UiPollingRate {
            get {
                return ((uint?)(this["UiPollingRate"]));
            }
            set {
                this["UiPollingRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint? UiMaxSpeedDelay {
            get {
                return ((uint?)(this["UiMaxSpeedDelay"]));
            }
            set {
                this["UiMaxSpeedDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UiHistoryEnabled {
            get {
                return ((bool)(this["UiHistoryEnabled"]));
            }
            set {
                this["UiHistoryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UiTopmostEnabled {
            get {
                return ((bool)(this["UiTopmostEnabled"]));
            }
            set {
                this["UiTopmostEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UiSaveWindowPos {
            get {
                return ((bool)(this["UiSaveWindowPos"]));
            }
            set {
                this["UiSaveWindowPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UiToolTipEnabled {
            get {
                return ((bool)(this["UiToolTipEnabled"]));
            }
            set {
                this["UiToolTipEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UiIsDarkTheme {
            get {
                return ((bool)(this["UiIsDarkTheme"]));
            }
            set {
                this["UiIsDarkTheme"] = value;
            }
        }
    }
}
